platform :ios, ‘8.0’

target ‘TestProject’ do
  use_frameworks!

  pod 'DZNEmptyDataSet'
  pod 'Mantle'
  pod 'Masonry'
  pod 'SAMKeychain'
  pod 'ReactiveObjC'
  pod 'ScreenCompatible_LFL'
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'IQKeyboardManager'
  pod 'Reachability'
  pod 'SDCycleScrollView'
  pod 'UITableView+FDTemplateLayoutCell'

end

